version: "3.0"

services:

  db:
    container_name: db-container
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - CREATE_DB=$CREATE_DB
      - DB_USER=$DB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/mysql
      - ./data/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./data/create_tables.sql:/create_tables.sql
    ports:
      - 3306:3306
    # networks:
    #   - app-network

  api:
    container_name: api-container
    build: ./api/.
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - API_PORT=$API_PORT
      - DATABASE_URL=mysql://${DB_USER}:${MYSQL_ROOT_PASSWORD}@db/${MYSQL_DATABASE}
    volumes:
      - ./api:/api
    ports:
      - ${API_PORT}:${API_PORT}
    # networks:
    #   - app-network

  app:
    container_name: app-container
    build: ./app/.
    depends_on:
      - api
    restart: unless-stopped
    environment:
      - APP_PORT=$APP_PORT
      - API_PORT=$API_PORT
      - API_HOST=$API_HOST
    volumes:
      - ./app:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.20.0.0/16
#           gateway: 172.20.0.1
